[package]
name = "LabelSoft"
version = "0.1.0"
authors = ["James Hardy <cyanjamesmail@gmail.com>"]
license = "GNU GPLv3"
edition = "2021"

[dependencies]
eframe = "0.30.0"
egui_extras = "0.30.0"
env_logger = "0.11.5"

